---
# Set AWS_SECRET_ACCESS_KEY and AWS_SECRET_KEY_ID facts
- name: Set AWS_ACCESS_KEY_ID
  shell:
    cmd: "awk -F'=' 'NR==2 { print $2 }' ~/.aws/credentials | sed -e 's/^[[:space:]]*//'"
  no_log: True
  register: aws_access_key_id

- name: Set AWS_SECRET_ACCESS_KEY
  shell:
    cmd: "awk -F'=' 'NR==3 { print $2 }' ~/.aws/credentials | sed -e 's/^[[:space:]]*//'"
  no_log: True
  register: aws_secret_access_key

- set_fact:
    AWS_ACCESS_KEY_ID: "{{ item }}"
  no_log: True
  with_items: "{{ aws_access_key_id.stdout }}"

- set_fact:
    AWS_SECRET_ACCESS_KEY: "{{ item }}"
  no_log: True
  with_items: "{{ aws_secret_access_key.stdout }}"

- name: Copy ssh_config to tmp dir
  shell:
    cmd: "cp ssh_config /tmp/ssh_config"
